openapi: "3.0.0"
info:
  version: "1.0.0"
  title: accountsapi
servers:
  - url: http://localhost:8081
paths:
  /accounts:
    get:
      summary: Get all accounts
      description: Retrieves a list of all accounts for Example Company
      responses:
        '200':
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    company_name:
                      type: string
                    phone_number:
                      type: string
                    address:
                      type: object
                      properties:
                        street:
                          type: string
                        city:
                          type: string
                        state:
                          type: string
                        postal_code:
                          type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: A message describing the error
                  timestamp:
                    type: string
                    format: date-time
                    description: The time at which the error occurred
